"""Dodanie flagi 'sprzedawca' do modelu kontrahent

Revision ID: 32c2f69f369
Revises: 5a62a9de050
Create Date: 2014-12-05 01:33:00.766111

"""

# revision identifiers, used by Alembic.
revision = '32c2f69f369'
down_revision = '5a62a9de050'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import core.utils.qvariantalchemy


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kwit_kontrahenci', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprzedawca', core.utils.qvariantalchemy.Boolean(), nullable=True))

    print('done!')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kwit_kontrahenci', schema=None) as batch_op:
        batch_op.drop_column('sprzedawca')

    ### end Alembic commands ###
