"""stworzenie modelu fakturanppozycja

Revision ID: 3dfe2b5da52
Revises: 32c2f69f369
Create Date: 2014-12-21 18:16:58.887672

"""

# revision identifiers, used by Alembic.
revision = '3dfe2b5da52'
down_revision = '32c2f69f369'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import core.utils.qvariantalchemy


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kwit_faktury_np')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kwit_faktury_np',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sprzedawca', sa.INTEGER(), nullable=True),
    sa.Column('nabywca', sa.INTEGER(), nullable=True),
    sa.Column('numer', sa.VARCHAR(), nullable=True),
    sa.Column('wystawiona', sa.DATETIME(), nullable=True),
    sa.Column('termin_platnosci', sa.DATETIME(), nullable=True),
    sa.Column('zaplacona', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['nabywca'], ['kwit_kontrahenci.id'], ),
    sa.ForeignKeyConstraint(['sprzedawca'], ['kwit_kontrahenci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
