"""Dodanie modelu Kontrahenta

Revision ID: 4717277a51e
Revises: 
Create Date: 2014-11-30 00:25:50.421107

"""

# revision identifiers, used by Alembic.
revision = '4717277a51e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import core.utils.qvariantalchemy

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kwit_kontrahenci',
    sa.Column('id', core.utils.qvariantalchemy.Integer(), nullable=False),
    sa.Column('nazwa', core.utils.qvariantalchemy.String(), nullable=True),
    sa.Column('nip', core.utils.qvariantalchemy.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kwit_kontrahenci')
    ### end Alembic commands ###
