"""dodanie kolumny z cena uslugi w walucie obcej

Revision ID: 4d9355a06b
Revises: 3dfe2b5da52
Create Date: 2014-12-24 03:54:47.136296

"""

# revision identifiers, used by Alembic.
revision = '4d9355a06b'
down_revision = '3dfe2b5da52'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import core.utils.qvariantalchemy


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kwit_faktury_np')
    op.drop_table('kwit_faktury_np_pozycje')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kwit_faktury_np_pozycje',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('faktura_np', sa.INTEGER(), nullable=True),
    sa.Column('usluga', sa.INTEGER(), nullable=True),
    sa.Column('cena', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['faktura_np'], ['kwit_faktury_np.id'], ),
    sa.ForeignKeyConstraint(['usluga'], ['kwit_uslugi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kwit_faktury_np',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sprzedawca', sa.INTEGER(), nullable=True),
    sa.Column('nabywca', sa.INTEGER(), nullable=True),
    sa.Column('numer', sa.VARCHAR(), nullable=True),
    sa.Column('wystawiona', sa.DATETIME(), nullable=True),
    sa.Column('termin_platnosci', sa.DATETIME(), nullable=True),
    sa.Column('zaplacona', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['nabywca'], ['kwit_kontrahenci.id'], ),
    sa.ForeignKeyConstraint(['sprzedawca'], ['kwit_kontrahenci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
