"""Dodanie pola adres

Revision ID: 5a62a9de050
Revises: 4717277a51e
Create Date: 2014-11-30 01:13:28.074204

"""

# revision identifiers, used by Alembic.
revision = '5a62a9de050'
down_revision = '4717277a51e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import core


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kwit_kontrahenci')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kwit_kontrahenci',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nazwa', sa.VARCHAR(), nullable=True),
    sa.Column('nip', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
